version: "3"
services:
  zaproxy:
    image: owasp/zap2docker-stable
    command: [
      "zap-webswing.sh",
      "-daemon",
      "-host", "0.0.0.0", "-port", "8080",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true"
    ]
    ports:
      - "127.0.0.1:8080:8080"

  juiceshop:
    image: bkimminich/juice-shop:latest
    ports:
      - "127.0.0.1:8082:3000"
